### ISSUE TITLE
Add US-SOUTH1 Dallas Region

### ISSUE THREAD

**Issue by dekirkpatrick** [GoogleCloudPlatform/gcping#117]
I ran your GCPing.com tool today for the first time to see what my latency would be like to Dallas (US-SOUTH1) and noticed it hasn't been included in your list yet. Can you please add this region when you have a chance? Thank you!

**Comment by kkr16** [comment]
Thank you for creating an issue @dekirkpatrick !
Dallas (us-south1) is now included in gcping.com results

fixed by https://github.com/GoogleCloudPlatform/gcping/pull/118

**Comment by dekirkpatrick** [comment]
That was quick! Thank you.
