### ISSUE TITLE
Update repo About snippet

### ISSUE THREAD

**Issue by imjasonh** [GoogleCloudPlatform/gcping#44]
It's still focused on the CLI tool and not both the CLI and the website.

<img width="336" alt="Screen Shot 2021-07-26 at 4 07 33 PM" src="https://user-images.githubusercontent.com/210737/127052068-dbc1d166-fb75-41b1-b9b4-ea209697e715.png">

I don't have permission to update it myself, or else I would 😄

**Comment by enocom** [comment]
Fixed! I meant to do that the other day. Thanks for the reminder. Feel free to re-open with better phrasing.
