### ISSUE TITLE
Use PerformanceTiming API to measure response time

### ISSUE THREAD

**Issue by yuryu** [GoogleCloudPlatform/gcping#55]
There's a web API to get the exact duration for each http request, which is more accurate than using Date and you can remove DNS lookup times.

https://developer.mozilla.org/en-US/docs/Web/API/Resource_Timing_API/Using_the_Resource_Timing_API

**Comment by enocom** [comment]
Very cool. Thanks for idea @yuryu.

**Comment by enocom** [comment]
Going to close this as a duplicate of #27.
