### ISSUE TITLE
Make the table header sticky

### ISSUE THREAD

**Issue by yuryu** [GoogleCloudPlatform/gcping#58]
As in the screenshot, it'd be helpful if the table header remains visible when you scroll down.

![image](https://user-images.githubusercontent.com/166481/132778850-db724895-cfc0-4eae-bf72-426665640018.png)

**Comment by yuryu** [comment]
Adding a video
https://user-images.githubusercontent.com/166481/132779245-db28a57e-8985-4641-96d5-e7686831a91f.mp4

**Comment by enocom** [comment]
This is really nice. I like it.

**Comment by crwilcox** [comment]
I also like this idea. I will make a PR, should be pretty targeted.
