### ISSUE TITLE
Windows release is redirecting to and error page.

### ISSUE THREAD

**Issue by themegabyte** [GoogleCloudPlatform/gcping#82]
Hello there,

I cannot download the windows compiled binary. Its redirecting to an error.

https://storage.googleapis.com/gcping-release/gcping_windows_amd64_latest

![image](https://user-images.githubusercontent.com/9980686/147505750-bc411795-d652-45cc-8dad-daa8b340ce93.png)

Thanks.

**Comment by enocom** [comment]
Thanks for the report. I’ll fix this.

**Comment by enocom** [comment]
The Windows binary is incorrectly named (arm64, should be amd64). If you use the following link you can download the amd64 binary in spite of the name. I'll republish with the correct name soon.

https://storage.googleapis.com/gcping-release/gcping_windows_arm64_latest

**Comment by enocom** [comment]
And now it's fixed. The correct URL is https://storage.googleapis.com/gcping-release/gcping_windows_amd64_latest.
